## Clase 09

Manejo de excepciones:

![](./121-assets/ppt-68-oop.png)

![](./121-assets/ppt-69-oop.png)

Error de sintaxis, algo está mal escrito en nuestro código. La única solución es corregirlo

![](./121-assets/ppt-70-oop.png)

Errores lógicas: por más que esté bien la redacción hay un problema en la lógica (en este ejemplo un archivo que no existe es `FileNotFoundError`, `ZeroDivisionError` o `ImportError`).

![](./121-assets/ppt-71-oop.png)

En estos casos sí debemos atrapar la excepción y gestionar el error (continuar con la ejecución del programa sin que este se interrumpa). Si no lo atrapamos la ejecución del programa se detiene.

Al hacer esto python crea un `objeto del tipo excepción.`

Ejemplos de excepción en el intérprete de python:

![](./121-assets/ppt-72-oop.png)

Principales tipos de excepción:

- TypeError
- ZeroDivisionError
- OverflowError
- IndexError
- KeyError
- FileNotFoundError
- ImportError

### Control de excepciones

![](./121-assets/ppt-73-oop.png)

Ejemplo `FileNotFoundError`:

![](./121-assets/ppt-74-oop.png)

> (!) Siempre deberíamos usar un try si nos estamos por conectar a otros ficheros, apis, base de datos, etc.

### Múltiples excepciones
Se pueden guardar las excepciones en una variable para acceder a sus argumentos:

![](./121-assets/ppt-75-oop.png)

### Finally
Se pueden ejecutar las sentencias ya sea que se produzca la excepción o no.

![](./121-assets/ppt-76-oop.png)

Generalmente usamos Finally para cerrar una conexión, ya sea que dio error o no.

### Parte práctica

![](./121-assets/ppt-77-oop.png)

Haciendo pruebas con manejo de errores:

![](./121-assets/ppt-78-oop.png)

Tipo de error personalizado:

![](./121-assets/ppt-79-oop.png)

Generamos nuestro propio tipo de excepción creando una clase que hereda de `Exception`

![](./121-assets/ppt-80-oop.png)

En línea 18 con raise lanzo la excepción con mi propio error que recibe un string.

### Ejercicio práctico en clase

![](./121-assets/ppt-81-oop.png)

Resolución:

```py

def agregar_una_vez(lista, elemento):

	if elemento not in lista:
		lista.append(elemento)
		print('se agregó un elemento a la lista!')
	else:
		raise ValueError('Error: Imposible añadir elementos duplicados', elemento)

def main():
	elementos = [1, 5, -2]
	add = [10, -2, 4, 'hola']  

	for i in add:
		try:
			agregar_una_vez(elementos, i)
			print(elementos)
		except Exception as e:
		print('error: ', e)

main()
```

> Archivo completo en /121-oop/python_files_oop/tarea-error/error_v1.py

